bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               OSGI-INF/,\
               icons/,\
               lib/api-25.4.5-SNAPSHOT.jar,\
               lib/azure-ai-openai-1.0.0-beta.14.jar,\
               lib/azure-core-1.55.2.jar,\
               lib/azure-core-http-netty-1.15.10.jar,\
               lib/azure-json-1.4.0.jar,\
               lib/azure-xml-1.2.0.jar,\
               lib/core-25.4.5-SNAPSHOT.jar,\
               lib/impl-25.4.5-SNAPSHOT.jar,\
               lib/jackson-annotations-2.18.3.jar,\
               lib/jackson-core-2.18.3.jar,\
               lib/jackson-databind-2.18.3.jar,\
               lib/jackson-datatype-jsr310-2.17.2.jar,\
               lib/jsoup-1.19.1.jar,\
               lib/jspecify-1.0.0.jar,\
               lib/jtokkit-1.1.0.jar,\
               lib/langchain4j-1.0.0-beta2.jar,\
               lib/langchain4j-azure-open-ai-1.0.0-beta2.jar,\
               lib/langchain4j-core-1.0.0-beta2.jar,\
               lib/langchain4j-http-client-jdk-1.0.0-beta2.jar,\
               lib/langchain4j-http-client-1.0.0-beta2.jar,\
               lib/langchain4j-ollama-1.0.0-beta2.jar,\
               lib/langchain4j-open-ai-1.0.0-beta2.jar,\
               lib/netty-buffer-4.1.118.Final.jar,\
               lib/netty-codec-4.1.118.Final.jar,\
               lib/netty-codec-dns-4.1.112.Final.jar,\
               lib/netty-codec-http-4.1.118.Final.jar,\
               lib/netty-codec-http2-4.1.118.Final.jar,\
               lib/netty-codec-socks-4.1.118.Final.jar,\
               lib/netty-common-4.1.118.Final.jar,\
               lib/netty-handler-4.1.118.Final.jar,\
               lib/netty-handler-proxy-4.1.118.Final.jar,\
               lib/netty-resolver-4.1.118.Final.jar,\
               lib/netty-resolver-dns-4.1.112.Final.jar,\
               lib/netty-resolver-dns-classes-macos-4.1.112.Final.jar,\
               lib/netty-resolver-dns-native-macos-4.1.112.Final-osx-x86_64.jar,\
               lib/netty-tcnative-boringssl-static-2.0.70.Final-linux-aarch_64.jar,\
               lib/netty-tcnative-boringssl-static-2.0.70.Final-linux-x86_64.jar,\
               lib/netty-tcnative-boringssl-static-2.0.70.Final-osx-aarch_64.jar,\
               lib/netty-tcnative-boringssl-static-2.0.70.Final-osx-x86_64.jar,\
               lib/netty-tcnative-boringssl-static-2.0.70.Final-windows-x86_64.jar,\
               lib/netty-tcnative-classes-2.0.70.Final.jar,\
               lib/netty-tcnative-boringssl-static-2.0.70.Final.jar,\
               lib/netty-transport-4.1.118.Final.jar,\
               lib/netty-transport-classes-epoll-4.1.118.Final.jar,\
               lib/netty-transport-classes-kqueue-4.1.118.Final.jar,\
               lib/netty-transport-native-epoll-4.1.118.Final-linux-x86_64.jar,\
               lib/netty-transport-native-kqueue-4.1.118.Final-osx-x86_64.jar,\
               lib/netty-transport-native-unix-common-4.1.118.Final.jar,\
               lib/opennlp-tools-1.9.4.jar,\
               lib/reactive-streams-1.0.4.jar,\
               lib/slf4j-nop-2.0.17.jar,\
               lib/slf4j-api-2.0.17.jar,\
               lib/reactor-netty-http-1.0.48.jar,\
               lib/reactor-netty-core-1.0.48.jar,\
               lib/reactor-core-3.4.41.jar
additional.bundles = org.eclipse.ui,\
                     org.eclipse.core.runtime,\
                     org.eclipse.jface.text,\
                     org.eclipse.ui.console,\
                     org.eclipse.ui.workbench.texteditor
source.. = src/
output.. = bin/
