name: Build
on:
  push:
    branches:
      - current
  pull_request: 
  workflow_dispatch:
permissions:
  contents: write
  packages: read
  actions: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: "-Djava.awt.headless=true"
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
    - name: Set up JDK 21
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12  # v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build and Test
      run: mvn -B verify
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/target/surefire-reports'
        if-no-files-found: ignore
        retention-days: 3
        compression-level: 9
        overwrite: true
  macos-arm64-dmg:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build macOS DMG
      run: mvn -B -DskipTests -DskipITs -ntp -P macos install
    - name: Standardize DMG filename
      run: |
        mkdir -p standardized
        cp desktop/target/*.dmg standardized/Manorrock-Assistant-arm64.dmg
    - name: Update SNAPSHOT release
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: softprops/action-gh-release@v1
      with:
        name: SNAPSHOT Build
        tag_name: SNAPSHOT
        prerelease: true
        files: standardized/Manorrock-Assistant-arm64.dmg
        draft: false
  macos-amd64-dmg:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build macOS DMG
      run: mvn -B -DskipTests -DskipITs -ntp -P macos install
    - name: Standardize DMG filename
      run: |
        mkdir -p standardized
        cp desktop/target/*.dmg standardized/Manorrock-Assistant-amd64.dmg
    - name: Update SNAPSHOT release
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: softprops/action-gh-release@v1
      with:
        name: SNAPSHOT Build
        tag_name: SNAPSHOT
        prerelease: true
        files: standardized/Manorrock-Assistant-amd64.dmg
        draft: false
  nbm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build NetBeans Module
        run: mvn -B -DskipTests -DskipITs -ntp install
      - name: Standardize NBM filename
        run: |
          mkdir -p standardized
          cp netbeans/target/*.nbm standardized/Manorrock-Assistant.nbm
      - name: Update SNAPSHOT release
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: softprops/action-gh-release@v1
        with:
          name: SNAPSHOT Build
          tag_name: SNAPSHOT
          prerelease: true
          files: standardized/Manorrock-Assistant.nbm
          draft: false
  vsix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12  # v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build VSCode extension
        run: mvn clean install
      - name: Standardize VSIX filename
        run: |
          mkdir -p standardized
          cp vscode/*.vsix standardized/Manorrock-Assistant.vsix
      - name: Upload VSCode extension to SNAPSHOT release
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: softprops/action-gh-release@v1
        with:
          name: SNAPSHOT Build
          tag_name: SNAPSHOT
          prerelease: true
          files: standardized/Manorrock-Assistant-arm64.vsix
          draft: false
